export const navLinks=[
    {
        id:1,
        url:'/#home',
        label:"Home"
    },
    {
        id:2,
        url:'/#about',
        label:"About"
    },
    {
        id:3,
        url:'/#destination',
        label:"Destination"
    },
    {
        id:4,
        url:'/#reviews',
        label:"Reviews"
    },
    {
        id:5,
        url:'/#services',
        label:"Services"
    },
    {
        id:6,
        url:'/#contact',
        label:"Contact"
    }
]